global using Endpoint.Engineering.DomainDrivenDesign;
global using Endpoint.Engineering.DomainDrivenDesign.Models;
global using Endpoint.Engineering.StaticAnalysis.Scss;
global using Endpoint.Engineering.StaticAnalysis;
global using Endpoint.Engineering.StaticAnalysis.Models;
global using Endpoint.Engineering.UnitTests.StaticAnalysis.AcceptanceTests;
global using Xunit;
global using Moq;
global using Microsoft.Extensions.Logging;
